version: '3'
services:
  tsdm_sign:
    image: ghcr.io/rsshiki/tedm_sign_docker:main
    container_name: tsdm_sign
  web:
    build: .
    ports:
      - "6865:6865"
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Shanghai